### ISSUE TITLE
Obtaining OpenGL Symbols (get_proc_address)

### ISSUE THREAD

**Issue by deltabeard** [libretro/libretro-samples#14]
Hi all,

I am currently trying to write a libretro core for mpv, which can use an OpenGL callback. As shown [here](https://github.com/mpv-player/mpv-examples/blob/master/libmpv/sdl/main.c#L22) we need to obtain OpenGL symbols, which is where I'm having problems.

I've read the [libretro-gl.pdf](https://github.com/libretro/libretro.github.com/blob/master/documents/libretro-gl.pdf) document and understand that I can use retro_hw_get_proc_address_t to obtain these OpenGL symbols.

I currently have:

> static void *get_proc_address_mpv(void *fn_ctx, const char *name)
> {
> 	printf("name: %s\n", name); //Debug
> 	return hw_render.get_proc_address(name);
> }

> bool retro_load_game(const struct retro_game_info *info)
> {
> 	-snip-
> 	if(mpv_opengl_cb_init_gl(mpv_gl, NULL, get_proc_address_mpv, NULL) < 0)
> 	{
> 		log_cb(RETRO_LOG_ERROR, "failed to initialize mpv GL context\n");
> 		return false;
> 	}
> 	-snip-
> }

The full source code is [here](https://github.com/deltabeard/mpv-libretro/blob/master/mpv-libretro.c).

But this produces a compile error:

> mpv-libretro.c:237:9: warning: ISO C forbids return between function pointer and ‘void *’ [-Wpedantic]
>   return hw_render.get_proc_address(name);
>          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

... and also segfaults when attempting to load the first OpenGL symbol (glGetString).

I've tried searching for other libretro cores that use get_proc_address but my search is littered with libretro.h which is in every libretro core repository.

Would you be able to point me in the right direction please?
I apologise if this isn't the best place to ask for assistance.

Thanks.

**Comment by inactive123** [comment]
Hi there,

sorry for the late response.

Try to look into the GL state machine we made for other cores like Parallel N64, for instance.

https://github.com/libretro/parallel-n64/blob/master/libretro-common/include/glsm/glsm.h#L133

https://github.com/libretro/parallel-n64/blob/master/libretro-common/glsm/glsm.c#L2252

If necessary, I could probably start writing a sample that will illustrate usage of this and should show it to work.

**Comment by twinaphex** [comment]
https://github.com/libretro/parallel-n64/blob/master/libretro-common/glsm/glsm.c#L2250

Try to include an early include - it might be the case that it takes some time for the hardware context to be initialized and ready before you can use it.

**Comment by inactive123** [comment]
Let me try compiling it on my Linux laptop to see if I could maybe get closer the problem.

**Comment by deltabeard** [comment]
Thanks for your response. I would be grateful if you wrote a sample to show how the GL state machine works, because I am quite lost. However, I'm not sure if the GL state machine is actually what I'm looking for.

When starting this project, I had a look at the SDL libmpv example file [here](https://github.com/mpv-player/mpv-examples/blob/master/libmpv/sdl/main.c#L22) and was hoping that libretro had a similar function to the SDL function "SDL_GL_GetProcAddress()" to return OpenGL symbols. Does libretro have anything similar? I had a look at both `retro_hw_get_proc_address_t get_proc_address;` and `retro_get_proc_address_t get_proc_address;` in libretro.h and thought that they would provide such functionality (although the latter returns a symbol from the libretro core rather than the other way round).

In case you want to compile [mpv-libretro](https://github.com/deltabeard/mpv-libretro) yourself, you need to compile ffmpeg (latest git) with `--enable-shared`, [mpv](https://github.com/mpv-player/mpv) (latest git) with `--enable-libmpv-shared` and then finally compile mpv-libretro.

Thanks for your help. Sorry if I'm misunderstanding OpenGL terminology.

**Comment by deltabeard** [comment]
Hi again.

I've tried to use your links to make an educated guess as to what I'm supposed to be doing. I've taken some code from this commit https://github.com/libretro/parallel-n64/commit/64e2a8fdd8b1c8c87de8eb39e2b173207c8dc7e3 but I'm getting loads `mpv-libretro/libretro-common/glsm/glsm.c:2158: undefined reference to 'glDepthFunc'` errors and I'm unsure how to resolve them. Considering the size of the parallel-n64 repo, I'm finding it difficult to find portions of code that I might find helpful.

If you could write sample code as per your suggestion earlier, that would be very helpful.

Thanks.

Edit: I pushed my changes [here](https://github.com/deltabeard/mpv-libretro/tree/glsm_wip).

**Comment by inactive123** [comment]
Hi there, 

I will make it a point to check out your code today. We are also in the middle of a RetroArch 1.7.0 release but I want to help here and guide you along, so that will happen today, guaranteed.

I agree with you on the need for there to be more samples, and will be happy to accomodate. We will start prioritizing that so that the barrier to entry can be lowered considerably.

Also, I will try to invite @Themaister since he would likely be able to lend his expertise as well. He is a heavy mpv fan as well, so that always helps :).

**Comment by deltabeard** [comment]
Thanks for your hospitality. Please take your time.
I've been using Retroarch (& libretro cores) and mpv for years and love them both; it's nice to finally have a reason to talk to you guys.

**Comment by deltabeard** [comment]
Hi. Have you had the opportunity to check out my code yet? Thanks.

**Comment by deltabeard** [comment]
Just a quick update, I've managed to get my code to compile successfully on the [glsm_wip branch](https://github.com/deltabeard/mpv-libretro/commits/glsm_wip). I've tried two different ways of obtaining proc addresses [here](https://github.com/deltabeard/mpv-libretro/blob/glsm_wip/mpv-libretro.c#L235) but neither of them work.

Would you be able to shed some light here? I have little programming knowledge of OpenGL, so I'm running out of ideas. Thanks.

**Comment by inactive123** [comment]
I am inviting @Alcaro to this conversation as well.

**Comment by Alcaro** [comment]
rglgen helps if you're going to call a large number of glFooBar functions yourself, but you're not doing that, so you don't need it.

Not sure about glsm, but I don't think it's useful without shared context, which iirc is off by default. I don't think you need that either.

To get rid of that function pointer warning, just add a void* cast. Can't find anything else that's obviously wrong with the function pointer setup, but I don't know much about GL.

However, I can find a few bugs later: You're forgetting to call video_cb, and you should pass hw_render.get_current_framebuffer() to mpv_opengl_cb_draw(), not 0.

**Comment by deltabeard** [comment]
> To get rid of that function pointer warning, just add a void* cast. Can't find anything else that's obviously wrong with the function pointer setup, but I don't know much about GL.

`hw_render.get_proc_address(name);` still returns NULL instead of a function pointer.

> You're forgetting to call video_cb, and you should pass hw_render.get_current_framebuffer() to mpv_opengl_cb_draw(), not 0.

I wanted to get the "get_proc" stuff working first so I actually have something to draw on the framebuffer. Currently mpv exits because it's unable to initialise an OpenGL context due to get_proc_address not working. But I will make these changes.

Thanks for your suggestions.

**Comment by deltabeard** [comment]
I used gdb to follow exactly what was happening when calling `hw_render.get_proc_address(name)`. The function `video_driver_get_proc_address(const char *sym)` in gfx/video_driver.c:648 returns NULL. Using gdb, I found that video_driver_poke was not initialised as shown below.
![2017-12-29-180343_954x1000_scrot](https://user-images.githubusercontent.com/3747104/34443986-bacd9620-ecc2-11e7-84a8-7334146d9bd9.png)


Is there a reason video_driver_poke is not initialised? I'm hoping this is the issue.
Thanks again.

Edit: it's not clear in the screenshot, but video_driver_poke is definitely NULL.

**Comment by inactive123** [comment]
Which video driver is being used?

**Comment by deltabeard** [comment]
`gl`. I also tried `sdl` and `vulkan` out of curiosity but they didn't work for obvious reasons.

**Comment by deltabeard** [comment]
I got the same with the latest Retroarch release, master branch and v1.3.6. Same result. get_process_address returns NULL.

**Comment by deltabeard** [comment]
Is this an issue with Retroarch? And if so, should we move this conversation to the Retroarch repository where it might get more attention?

**Comment by deltabeard** [comment]
@twinaphex could we get the ball rolling on this issue please?

ffmpeg_core uses hw_render.get_proc_address [here](https://github.com/libretro/RetroArch/blob/99f696abd2d1ecbd68237abd12c2bbbba3c04d3e/cores/libretro-ffmpeg/ffmpeg_core.c#L1404) and parallel-n64 does the same [here](https://github.com/libretro/parallel-n64/blob/ed78991066e684dd4319bae0d6e8a5cdad01e5ed/libretro-common/glsm/glsm.c). They don't seem to be doing anything special other than call `rglgen_resolve_symbols(hw_render.get_proc_address)` which @Alcaro  said that I didn't need to use.

However, libmpv which is linked to mpv-libretro does require those OpenGL symbols. Does that mean that I require rglgen or not?

There's barely any documentation on hw_render.get_proc_address() so I can't progress until I get some feedback.

I can't find any documentation on video_driver_poke and what is required for it to work.

**Comment by inactive123** [comment]
I very much doubt it is an issue with RetroArch, what I suspect is going on is that MPV tries to initialize itself BEFORE the GL hardware context has had a chance to initialize itself yet. You should delay initialization of the renderer of your program UNTIL the GL hardware context is ready to be used. This is just me guessing though based on how MPV is likely to be implemented under the hood.

@Themaister Care to respond to any of this too? We really need some more active feedback here in case we want people to actually use our APIs.

**Comment by deltabeard** [comment]
Thanks for the reply! I added the initialisation of MPV in a while loop as follows:

> 	while(mpv_opengl_cb_init_gl(mpv_gl, NULL, get_proc_address_mpv, NULL) < 0)
	{
		static unsigned int failnum = 0;
		printf("\33[2K\rFailed %d times", ++failnum);
		usleep(10);
	}
	printf("\n");

Where get_proc_address_mpv() calls hw_render.get_proc_address() as before. It still doesn't work. It printed "Failed 942784 times", where I waited about 10 seconds before killing the program which I thought was ample time for GL to initialise.

I'm still going to play around with this. I'm setting various different breakpoints in gdb, but I highly doubt I'll get anywhere.

Edit: I've also tried reverting what I did above, and just adding a sleep(10) before mpv initialises opengl and that didn't work.

**Comment by inactive123** [comment]
Does mpv use ffmpeg under the hood?

**Comment by deltabeard** [comment]
Yes

**Comment by inactive123** [comment]
What major parts are different then vs. ffmpeg in terms of initialization? We made an existing ffmpeg libretro implementation - not sure of how much use that would be to you. It does not use OpenGL though, it just employs software rendering. What do you need OpenGL for when it comes to this core? For overlays, hardware decoding, etc.?

This is the source code to our existing ffmpeg libretro core -

https://github.com/libretro/RetroArch/tree/master/cores/libretro-ffmpeg

**Comment by deltabeard** [comment]
libmpv uses a OpenGL callback feature that takes a foreign OpenGL context and draws to it as described [here](https://github.com/mpv-player/mpv/blob/master/libmpv/opengl_cb.h). libmpv has a second method of drawing video (using "wid") but it isn't preferred and I'm not sure how that would work with Retroarch.

I think libmpv uses OpenGL is used to draw everything on to the screen, including subtitles.

By using the OpenGL callback, I was hoping to achieve hardware acceleration for systems that already support it with mpv.

As for the differences in initialisation, I'm not sure. I haven't dabbled with ffmpeg much. But I believe libmpv is much simpler as that handles codec selection, resampling, etc.

**Comment by inactive123** [comment]
As for the hardware acceleration, is video decoding a part of that?

Is that not handled by libvdpau and other APIs like that instead of GL itself?

**Comment by deltabeard** [comment]
According to [this](https://github.com/mpv-player/mpv/blob/master/libmpv/opengl_cb.h#L129) it can use external libraries like libvdpau for hardware acceleration, otherwise it can use EGL. However, the "hwdec" option needs to be enabled for libmpv to use hardware decoding, which it currently isn't.

**Comment by Alcaro** [comment]
Aren't you supposed to not use GL until the frontend calls the context_reset callback?

...though that means you can't fail loading the game depending on the host's GL capabilities, other than demanding a minimum GL version... and I'm not sure if rarch fails if you ask for some silly version...

**Comment by deltabeard** [comment]
Woo! Initialising mpv and it's gl functions in context_reset worked! I'll post more information and my code shortly.

**Comment by deltabeard** [comment]
So I refactored the code and moved mpv initialisation functions into context_reset. I had to store the filename in a global variable, and as @Alcaro has said, I can't error out of context_reset should anything fail. So I will probably have to add good logging and an abort() instead of a return.

Here's a log file showing get_proc_address now working: [log.txt](https://github.com/libretro/libretro-samples/files/1596285/log.txt)

mpv-libretro now seg-faults when attempting to draw a frame, but I think I should be able to take it from here.

Thank you everyone for the help.

**Comment by inactive123** [comment]
And yes, what Alcaro says is correct and is also what I hinted at earlier - until the context_reset callback is called, you are not supposed to assume you can use anything related to the GL HW context yet. This is likely why video_driver_poke was set to NULL before when you were trying to use the get_proc_address callback - the frontend (in this case RetroArch ) did not have a chance yet to properly initialize the hardware context yet.

**Comment by inactive123** [comment]
Hey @deltabeard , I see in your repo that it's off to a great start. Excited to see the progress on this core! Keep us in the loop if you'd like when there are new developments

**Comment by deltabeard** [comment]
Sure! I'm quite excited too. 😄 @twinaphex where would be the best place to post progress updates?

**Comment by inactive123** [comment]
well, if you would like, i could give you access to our blog on libretro.com, you could weite blog posts there on this core.

Also, you are welcome to visit us on discord. We as a development team hang out there, probably best way to connect with us in realtime. We would be glad to meet you.

**Comment by deltabeard** [comment]
That would be great! My discord tag is Deltabeard#2356 (in case that's required - I'm newish to discord)
