### ISSUE TITLE
Samples for the frontend side

### ISSUE THREAD

**Issue by obbardc** [libretro/libretro-samples#25]
hi!

There are lots of nice samples here for creating a core, but can you point me on how best to get started with loading cores and setting up everything to play a game in a core ?

If there are no specific examples, just a bit of direction on where the code exists to get started would be great.

**Comment by obbardc** [comment]
So far the simplest example I could find was https://github.com/heuripedes/sdlarch

**Comment by gouchi** [comment]
Hi,

You can check also [Mininal reference frontend](https://github.com/bparker06/reference_frontend), [Nanoarch](https://github.com/heuripedes/nanoarch), [Miniretro](https://github.com/davidgfnet/miniretro).

If you need more examples, you may check this [list](https://docs.libretro.com/development/frontends/).

Thank you.
